### ISSUE TITLE
[Edit Proflie] Edit profile require `socials.email` field

### ISSUE THREAD

**Issue by cunbidun** [Saakshaat/projectory#16]
**Describe the bug**
Edit profile require `socials.email` field. Since users are not allowed to edit their email address, it's not necessary to return `email` field within `socials` object. In addition to this, if client doesn't include `email` field in the request, the sever will remove it from `socials` object.

**Comment by Saakshaat** [comment]
Fixed in 2b6af722fb910f69b14469353d9064f6d638a8fb
