### ISSUE TITLE
API for allowing users to select which skills to show on their Profile Snapshot Card

### ISSUE THREAD

**Issue by cunbidun** [Saakshaat/projectory#7]
**Context**
I think the Profile Snapshot Card would be more informative if we could show some skills of users.
However, one user can have a lot of skills, so there is a good chance we don't have enough space in the card to show all of them. 

**Request**
It would be nice we allow users to select some of their best skills (at most 5?) to show on their Profile Snapshot Card. To do this, we need an API to get user top skills.

**Addition Usage**
We can show those skills first on users' profiles.

**Comment by Saakshaat** [comment]
Implemented `top` and `other` subfields for skills in the `experience` collection. Now the user can enter their top skills and other skills during profile creation and updation. These fields will be returned respectively when the client makes a `GET` request to show the profile.

The new request would look like this

```
{
    "uid": "TbbyD06g45Uk3slqaQpz5v5Calh1",
    "credentials": {
        "email": "newfield@gmail.com",
        "provider": "email",
        "createdAt": "Thu, 14 May 2020 18:13:10 GMT"
    },
    "information": {
        "name": "New fields",
        "bio": "I am the new fields for skills, namely top and others. I also have new fields for website and email in the user's socials. I have been refactored by Saakshaat in the profile creation and showing a single profile. I still need to be implemented in displaying multiple profiles.",
        "institution": "None",
        "socials": {
            "github": "https://github.com/oscar",
            "linkedin": "https://linkedin.com/in/oscar",
            "website": "https://newFields.com"
        }
    },
    "experience": {
    	"headline": "Software Product Consumer Chain",
        "skills": {
            "top": [
            	"Java",
            	"C++",
            	"React.js"
            	],
        	"other": [
        		"Github",
        		"Docker",
        		"Kubernetes",
        		"Database management"
        		]
        }
    }
}
```
